# Generated by Django 2.0.1 on 2018-01-27 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
